name: Sync Conservation Package

on:
  push:
    branches:
      - main
    paths:
      - 'conservation/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          path: main-repo

      - name: Checkout conservation repository
        uses: actions/checkout@v3
        with:
          repository: Istionia/featherpause-conservation
          path: conservation-repo
          token: ${{ secrets.CONSERVATION_SYNC_TOKEN }}

      - name: Sync files
        run: |
          # Remove everything except .git
          find conservation-repo -mindepth 1 -maxdepth 1 -not -path "conservation-repo/.git" -exec rm -rf {} \;
          
          # Copy all files from the conservation package
          cp -R main-repo/conservation/* conservation-repo/
          
          # Set up git in the conservation repo
          cd conservation-repo
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          # Add and commit changes if there are any
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync from main repository [${GITHUB_SHA:0:7}]"
            git push
          fi 